package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:11:11.856-03:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ControladorUsuarioPublishService",
                  wsdlLocation = "http://localhost:3030/controladorUsuario?wsdl",
                  targetNamespace = "http://publicadores/")
public class ControladorUsuarioPublishService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://publicadores/", "ControladorUsuarioPublishService");
    public final static QName ControladorUsuarioPublishPort = new QName("http://publicadores/", "ControladorUsuarioPublishPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:3030/controladorUsuario?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControladorUsuarioPublishService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:3030/controladorUsuario?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControladorUsuarioPublishService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControladorUsuarioPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorUsuarioPublishService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ControladorUsuarioPublishService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ControladorUsuarioPublishService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ControladorUsuarioPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ControladorUsuarioPublish
     */
    @WebEndpoint(name = "ControladorUsuarioPublishPort")
    public ControladorUsuarioPublish getControladorUsuarioPublishPort() {
        return super.getPort(ControladorUsuarioPublishPort, ControladorUsuarioPublish.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorUsuarioPublish
     */
    @WebEndpoint(name = "ControladorUsuarioPublishPort")
    public ControladorUsuarioPublish getControladorUsuarioPublishPort(WebServiceFeature... features) {
        return super.getPort(ControladorUsuarioPublishPort, ControladorUsuarioPublish.class, features);
    }

}
