package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:27.102-03:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ControladorEspectaculoPublishService",
                  wsdlLocation = "http://localhost:3030/controladorEsp?wsdl",
                  targetNamespace = "http://publicadores/")
public class ControladorEspectaculoPublishService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://publicadores/", "ControladorEspectaculoPublishService");
    public final static QName ControladorEspectaculoPublishPort = new QName("http://publicadores/", "ControladorEspectaculoPublishPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:3030/controladorEsp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControladorEspectaculoPublishService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:3030/controladorEsp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControladorEspectaculoPublishService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControladorEspectaculoPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorEspectaculoPublishService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ControladorEspectaculoPublishService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ControladorEspectaculoPublishService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ControladorEspectaculoPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ControladorEspectaculoPublish
     */
    @WebEndpoint(name = "ControladorEspectaculoPublishPort")
    public ControladorEspectaculoPublish getControladorEspectaculoPublishPort() {
        return super.getPort(ControladorEspectaculoPublishPort, ControladorEspectaculoPublish.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorEspectaculoPublish
     */
    @WebEndpoint(name = "ControladorEspectaculoPublishPort")
    public ControladorEspectaculoPublish getControladorEspectaculoPublishPort(WebServiceFeature... features) {
        return super.getPort(ControladorEspectaculoPublishPort, ControladorEspectaculoPublish.class, features);
    }

}
