package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:27.092-03:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://publicadores/", name = "ControladorEspectaculoPublish")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ControladorEspectaculoPublish {

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/seleccionarFuncionRequest", output = "http://publicadores/ControladorEspectaculoPublish/seleccionarFuncionResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/seleccionarFuncion/Fault/Exception")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtFuncion seleccionarFuncion(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/getDTRequest", output = "http://publicadores/ControladorEspectaculoPublish/getDTResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/getDT/Fault/Exception")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtEspectaculoCompleto getDT(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/seleccionarPaqueteRequest", output = "http://publicadores/ControladorEspectaculoPublish/seleccionarPaqueteResponse", fault = {@FaultAction(className = PaqueteNoValidoException_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/seleccionarPaquete/Fault/PaqueteNoValidoException")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtPaquete seleccionarPaquete(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws PaqueteNoValidoException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/ingresarEspectaculoRequest", output = "http://publicadores/ControladorEspectaculoPublish/ingresarEspectaculoResponse", fault = {@FaultAction(className = PlataformaNoExisteException_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/ingresarEspectaculo/Fault/PlataformaNoExisteException"), @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/ingresarEspectaculo/Fault/UsuarioNoExisteException")})
    public void ingresarEspectaculo(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        DtEspectaculo arg2,
        @WebParam(partName = "arg3", name = "arg3")
        byte[] arg3
    ) throws PlataformaNoExisteException_Exception, UsuarioNoExisteException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/altaEspectaculoRequest", output = "http://publicadores/ControladorEspectaculoPublish/altaEspectaculoResponse")
    public void altaEspectaculo()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/getImagenFuncionRequest", output = "http://publicadores/ControladorEspectaculoPublish/getImagenFuncionResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/getImagenFuncion/Fault/Exception")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public java.lang.String getImagenFuncion(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/chequearDisponibilidadNombreRequest", output = "http://publicadores/ControladorEspectaculoPublish/chequearDisponibilidadNombreResponse", fault = {@FaultAction(className = EspectaculoNoValidoException_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/chequearDisponibilidadNombre/Fault/EspectaculoNoValidoException")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public boolean chequearDisponibilidadNombre(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws EspectaculoNoValidoException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/listarEspectaculosRequest", output = "http://publicadores/ControladorEspectaculoPublish/listarEspectaculosResponse", fault = {@FaultAction(className = PlataformaNoExisteException_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/listarEspectaculos/Fault/PlataformaNoExisteException")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarEspectaculos(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws PlataformaNoExisteException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorEspectaculoPublish/seleccionarEspectaculoRequest", output = "http://publicadores/ControladorEspectaculoPublish/seleccionarEspectaculoResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorEspectaculoPublish/seleccionarEspectaculo/Fault/Exception")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtEspectaculoCompleto seleccionarEspectaculo(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;
}
