
package publicadores;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:26.961-03:00
 * Generated source version: 3.4.4
 *
 */
public final class ControladorEspectaculoPublish_ControladorEspectaculoPublishPort_Client {

    private static final QName SERVICE_NAME = new QName("http://publicadores/", "ControladorEspectaculoPublishService");

    private ControladorEspectaculoPublish_ControladorEspectaculoPublishPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ControladorEspectaculoPublishService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ControladorEspectaculoPublishService ss = new ControladorEspectaculoPublishService(wsdlURL, SERVICE_NAME);
        ControladorEspectaculoPublish port = ss.getControladorEspectaculoPublishPort();

        {
        System.out.println("Invoking seleccionarFuncion...");
        java.lang.String _seleccionarFuncion_arg0 = "_seleccionarFuncion_arg01742463194";
        try {
            publicadores.DtFuncion _seleccionarFuncion__return = port.seleccionarFuncion(_seleccionarFuncion_arg0);
            System.out.println("seleccionarFuncion.result=" + _seleccionarFuncion__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getDT...");
        java.lang.String _getDT_arg0 = "_getDT_arg0-154517413";
        try {
            publicadores.DtEspectaculoCompleto _getDT__return = port.getDT(_getDT_arg0);
            System.out.println("getDT.result=" + _getDT__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking seleccionarPaquete...");
        java.lang.String _seleccionarPaquete_arg0 = "_seleccionarPaquete_arg0-1002606618";
        try {
            publicadores.DtPaquete _seleccionarPaquete__return = port.seleccionarPaquete(_seleccionarPaquete_arg0);
            System.out.println("seleccionarPaquete.result=" + _seleccionarPaquete__return);

        } catch (PaqueteNoValidoException_Exception e) {
            System.out.println("Expected exception: PaqueteNoValidoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking ingresarEspectaculo...");
        java.lang.String _ingresarEspectaculo_arg0 = "_ingresarEspectaculo_arg0-1433482828";
        java.lang.String _ingresarEspectaculo_arg1 = "_ingresarEspectaculo_arg12041173709";
        publicadores.DtEspectaculo _ingresarEspectaculo_arg2 = new publicadores.DtEspectaculo();
        _ingresarEspectaculo_arg2.setCantMax(-1850027344);
        _ingresarEspectaculo_arg2.setCantMin(1025324623);
        _ingresarEspectaculo_arg2.setCosto(0.85825557f);
        _ingresarEspectaculo_arg2.setDescripcion("Descripcion1292062883");
        _ingresarEspectaculo_arg2.setDuracion(89350722);
        _ingresarEspectaculo_arg2.setFechaReg(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:10:27.028-03:00"));
        _ingresarEspectaculo_arg2.setFechaRegString("FechaRegString-466519032");
        _ingresarEspectaculo_arg2.setNombre("Nombre1824422924");
        _ingresarEspectaculo_arg2.setOrganizador("Organizador-570393226");
        _ingresarEspectaculo_arg2.setPlataforma("Plataforma241942533");
        _ingresarEspectaculo_arg2.setURL("URL-1561446880");
        byte[] _ingresarEspectaculo_arg3 = new byte[] {};
        try {
            port.ingresarEspectaculo(_ingresarEspectaculo_arg0, _ingresarEspectaculo_arg1, _ingresarEspectaculo_arg2, _ingresarEspectaculo_arg3);

        } catch (PlataformaNoExisteException_Exception e) {
            System.out.println("Expected exception: PlataformaNoExisteException has occurred.");
            System.out.println(e.toString());
        } catch (UsuarioNoExisteException_Exception e) {
            System.out.println("Expected exception: UsuarioNoExisteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking altaEspectaculo...");
        port.altaEspectaculo();


        }
        {
        System.out.println("Invoking getImagenFuncion...");
        java.lang.String _getImagenFuncion_arg0 = "_getImagenFuncion_arg0-1041759861";
        try {
            java.lang.String _getImagenFuncion__return = port.getImagenFuncion(_getImagenFuncion_arg0);
            System.out.println("getImagenFuncion.result=" + _getImagenFuncion__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking chequearDisponibilidadNombre...");
        java.lang.String _chequearDisponibilidadNombre_arg0 = "_chequearDisponibilidadNombre_arg0630256306";
        try {
            boolean _chequearDisponibilidadNombre__return = port.chequearDisponibilidadNombre(_chequearDisponibilidadNombre_arg0);
            System.out.println("chequearDisponibilidadNombre.result=" + _chequearDisponibilidadNombre__return);

        } catch (EspectaculoNoValidoException_Exception e) {
            System.out.println("Expected exception: EspectaculoNoValidoException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking listarEspectaculos...");
        java.lang.String _listarEspectaculos_arg0 = "_listarEspectaculos_arg01162202338";
        try {
            net.java.dev.jaxb.array.StringArray _listarEspectaculos__return = port.listarEspectaculos(_listarEspectaculos_arg0);
            System.out.println("listarEspectaculos.result=" + _listarEspectaculos__return);

        } catch (PlataformaNoExisteException_Exception e) {
            System.out.println("Expected exception: PlataformaNoExisteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking seleccionarEspectaculo...");
        java.lang.String _seleccionarEspectaculo_arg0 = "_seleccionarEspectaculo_arg02058832237";
        try {
            publicadores.DtEspectaculoCompleto _seleccionarEspectaculo__return = port.seleccionarEspectaculo(_seleccionarEspectaculo_arg0);
            System.out.println("seleccionarEspectaculo.result=" + _seleccionarEspectaculo__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
