
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package publicadores;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:09:52.697-03:00
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
                      serviceName = "ControladorPaquetePublishService",
                      portName = "ControladorPaquetePublishPort",
                      targetNamespace = "http://publicadores/",
                      wsdlLocation = "http://localhost:3030/controladorPaq?wsdl",
                      endpointInterface = "publicadores.ControladorPaquetePublish")

public class ControladorPaquetePublishPortImpl implements ControladorPaquetePublish {

    private static final Logger LOG = Logger.getLogger(ControladorPaquetePublishPortImpl.class.getName());

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#chequearDisponibilidadPaquete(java.lang.String arg0)*
     */
    public boolean chequearDisponibilidadPaquete(java.lang.String arg0) {
        LOG.info("Executing operation chequearDisponibilidadPaquete");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#agregarEspectaculoAPaquete(java.lang.String arg0)*
     */
    public void agregarEspectaculoAPaquete(java.lang.String arg0) {
        LOG.info("Executing operation agregarEspectaculoAPaquete");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#listarPaquetesVigentes()*
     */
    public net.java.dev.jaxb.array.StringArray listarPaquetesVigentes() {
        LOG.info("Executing operation listarPaquetesVigentes");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1948518330";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#getImagenPaquete(java.lang.String arg0)*
     */
    public java.lang.String getImagenPaquete(java.lang.String arg0) throws Exception_Exception   {
        LOG.info("Executing operation getImagenPaquete");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1715839908";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#seleccionarEspectaculo(java.lang.String arg0)*
     */
    public publicadores.DtEspectaculoCompleto seleccionarEspectaculo(java.lang.String arg0) throws Exception_Exception   {
        LOG.info("Executing operation seleccionarEspectaculo");
        System.out.println(arg0);
        try {
            publicadores.DtEspectaculoCompleto _return = new publicadores.DtEspectaculoCompleto();
            _return.setCantMax(-301681109);
            _return.setCantMin(-2012769981);
            _return.setCosto(0.27688265f);
            _return.setDescripcion("Descripcion2124564192");
            _return.setDuracion(-1456498089);
            _return.setFechaReg(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:09:52.708-03:00"));
            _return.setFechaRegString("FechaRegString329016752");
            _return.setNombre("Nombre1840750918");
            _return.setOrganizador("Organizador1397626709");
            _return.setPlataforma("Plataforma-293462986");
            _return.setURL("URL-422700427");
            java.util.List<java.lang.String> _returnFuncionesAsociadas = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnFuncionesAsociadasVal1 = "_returnFuncionesAsociadasVal-100442274";
            _returnFuncionesAsociadas.add(_returnFuncionesAsociadasVal1);
            _return.getFuncionesAsociadas().addAll(_returnFuncionesAsociadas);
            java.util.List<java.lang.String> _returnPaquetesAsociados = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPaquetesAsociadosVal1 = "_returnPaquetesAsociadosVal822488190";
            _returnPaquetesAsociados.add(_returnPaquetesAsociadosVal1);
            _return.getPaquetesAsociados().addAll(_returnPaquetesAsociados);
            _return.setImagen("Imagen1018967846");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#seleccionarPlataforma(java.lang.String arg0, java.lang.String arg1)*
     */
    public net.java.dev.jaxb.array.StringArray seleccionarPlataforma(java.lang.String arg0, java.lang.String arg1) throws PlataformaNoValidaException_Exception   {
        LOG.info("Executing operation seleccionarPlataforma");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal2112855188";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PlataformaNoValidaException_Exception("PlataformaNoValidaException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#seleccionarPaquete(java.lang.String arg0)*
     */
    public publicadores.DtPaquete seleccionarPaquete(java.lang.String arg0) {
        LOG.info("Executing operation seleccionarPaquete");
        System.out.println(arg0);
        try {
            publicadores.DtPaquete _return = new publicadores.DtPaquete();
            _return.setDescripcion("Descripcion-521125325");
            _return.setDescuento(0.38387036f);
            java.util.List<java.lang.String> _returnEspectaculos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnEspectaculosVal1 = "_returnEspectaculosVal1575041638";
            _returnEspectaculos.add(_returnEspectaculosVal1);
            _return.getEspectaculos().addAll(_returnEspectaculos);
            _return.setFechaFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:09:52.710-03:00"));
            _return.setFechaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:09:52.711-03:00"));
            _return.setFechaRegistro(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:09:52.711-03:00"));
            _return.setNombre("Nombre-2057585583");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#comprarPaquete(java.lang.String arg0, java.lang.String arg1)*
     */
    public void comprarPaquete(java.lang.String arg0, java.lang.String arg1) throws Exception_Exception   {
        LOG.info("Executing operation comprarPaquete");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#listarPaquetes()*
     */
    public net.java.dev.jaxb.array.StringArray listarPaquetes() {
        LOG.info("Executing operation listarPaquetes");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-708455850";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#espectaculosDelPaquete(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray espectaculosDelPaquete(java.lang.String arg0) {
        LOG.info("Executing operation espectaculosDelPaquete");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal24848676";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#altaPaquete()*
     */
    public void altaPaquete() throws PaqueteNoValidoException_Exception   {
        LOG.info("Executing operation altaPaquete");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PaqueteNoValidoException_Exception("PaqueteNoValidoException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPaquetePublish#ingresarDatosPaquete(publicadores.DtPaquete arg0, byte[] arg1)*
     */
    public void ingresarDatosPaquete(DtPaquete arg0, byte[] arg1) throws PaqueteNoValidoException_Exception   {
        LOG.info("Executing operation ingresarDatosPaquete");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PaqueteNoValidoException_Exception("PaqueteNoValidoException...");
    }

}
