package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:10.901-03:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://publicadores/", name = "ControladorPlataformaPublish")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ControladorPlataformaPublish {

    @WebMethod
    @Action(input = "http://publicadores/ControladorPlataformaPublish/altaPlataformaRequest", output = "http://publicadores/ControladorPlataformaPublish/altaPlataformaResponse", fault = {@FaultAction(className = PlataformaNoValidaException_Exception.class, value = "http://publicadores/ControladorPlataformaPublish/altaPlataforma/Fault/PlataformaNoValidaException")})
    public void altaPlataforma()
 throws PlataformaNoValidaException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPlataformaPublish/listaPlataformasRequest", output = "http://publicadores/ControladorPlataformaPublish/listaPlataformasResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listaPlataformas()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPlataformaPublish/chequearDisponibilidadPlataformaRequest", output = "http://publicadores/ControladorPlataformaPublish/chequearDisponibilidadPlataformaResponse", fault = {@FaultAction(className = PlataformaNoValidaException_Exception.class, value = "http://publicadores/ControladorPlataformaPublish/chequearDisponibilidadPlataforma/Fault/PlataformaNoValidaException")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public boolean chequearDisponibilidadPlataforma(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws PlataformaNoValidaException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPlataformaPublish/ingresarDatosPlataformaRequest", output = "http://publicadores/ControladorPlataformaPublish/ingresarDatosPlataformaResponse", fault = {@FaultAction(className = PlataformaNoValidaException_Exception.class, value = "http://publicadores/ControladorPlataformaPublish/ingresarDatosPlataforma/Fault/PlataformaNoValidaException")})
    public void ingresarDatosPlataforma(

        @WebParam(partName = "arg0", name = "arg0")
        DtPlataforma arg0
    ) throws PlataformaNoValidaException_Exception;
}
