package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:41.940-03:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ControladorFuncionPublishService",
                  wsdlLocation = "http://localhost:3030/controladorFun?wsdl",
                  targetNamespace = "http://publicadores/")
public class ControladorFuncionPublishService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://publicadores/", "ControladorFuncionPublishService");
    public final static QName ControladorFuncionPublishPort = new QName("http://publicadores/", "ControladorFuncionPublishPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:3030/controladorFun?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControladorFuncionPublishService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:3030/controladorFun?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControladorFuncionPublishService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControladorFuncionPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorFuncionPublishService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ControladorFuncionPublishService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ControladorFuncionPublishService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ControladorFuncionPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ControladorFuncionPublish
     */
    @WebEndpoint(name = "ControladorFuncionPublishPort")
    public ControladorFuncionPublish getControladorFuncionPublishPort() {
        return super.getPort(ControladorFuncionPublishPort, ControladorFuncionPublish.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorFuncionPublish
     */
    @WebEndpoint(name = "ControladorFuncionPublishPort")
    public ControladorFuncionPublish getControladorFuncionPublishPort(WebServiceFeature... features) {
        return super.getPort(ControladorFuncionPublishPort, ControladorFuncionPublish.class, features);
    }

}
