
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package publicadores;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:41.897-03:00
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
                      serviceName = "ControladorFuncionPublishService",
                      portName = "ControladorFuncionPublishPort",
                      targetNamespace = "http://publicadores/",
                      wsdlLocation = "http://localhost:3030/controladorFun?wsdl",
                      endpointInterface = "publicadores.ControladorFuncionPublish")

public class ControladorFuncionPublishPortImpl implements ControladorFuncionPublish {

    private static final Logger LOG = Logger.getLogger(ControladorFuncionPublishPortImpl.class.getName());

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#seleccionarFuncion(java.lang.String arg0)*
     */
    public publicadores.DtFuncion seleccionarFuncion(java.lang.String arg0) throws FuncionNoValidaException_Exception   {
        LOG.info("Executing operation seleccionarFuncion");
        System.out.println(arg0);
        try {
            publicadores.DtFuncion _return = new publicadores.DtFuncion();
            java.util.List<java.lang.String> _returnArtistasInvitados = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnArtistasInvitadosVal1 = "_returnArtistasInvitadosVal403556630";
            _returnArtistasInvitados.add(_returnArtistasInvitadosVal1);
            _return.getArtistasInvitados().addAll(_returnArtistasInvitados);
            _return.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:10:41.910-03:00"));
            _return.setFechaReg(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:10:41.911-03:00"));
            _return.setFechaRegString("FechaRegString784690772");
            _return.setFechaString("FechaString502041235");
            _return.setHoraIni(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:10:41.911-03:00"));
            _return.setHoraIniString("HoraIniString-414313944");
            _return.setNombre("Nombre-75643921");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FuncionNoValidaException_Exception("FuncionNoValidaException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#listarRegistros(java.lang.String arg0)*
     */
    public publicadores.DtRegistroCompletoArray listarRegistros(java.lang.String arg0) throws Exception_Exception   {
        LOG.info("Executing operation listarRegistros");
        System.out.println(arg0);
        try {
            publicadores.DtRegistroCompletoArray _return = new publicadores.DtRegistroCompletoArray();
            java.util.List<publicadores.DtRegistroCompleto> _returnItem = new java.util.ArrayList<publicadores.DtRegistroCompleto>();
            publicadores.DtRegistroCompleto _returnItemVal1 = new publicadores.DtRegistroCompleto();
            _returnItemVal1.setCosto(0.41201735f);
            _returnItemVal1.setFechaReg(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:10:41.913-03:00"));
            _returnItemVal1.setNombreFuncion("NombreFuncion-1364367889");
            _returnItemVal1.setId(873784888);
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#altaRegistroPaquete(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public void altaRegistroPaquete(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) throws Exception_Exception   {
        LOG.info("Executing operation altaRegistroPaquete");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#chequearDisponibilidadNombreFuncion(java.lang.String arg0)*
     */
    public boolean chequearDisponibilidadNombreFuncion(java.lang.String arg0) throws FuncionNoValidaException_Exception   {
        LOG.info("Executing operation chequearDisponibilidadNombreFuncion");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FuncionNoValidaException_Exception("FuncionNoValidaException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#listarFuncionesEspectador(java.lang.String arg0)*
     */
    public publicadores.DtFuncionArray listarFuncionesEspectador(java.lang.String arg0) {
        LOG.info("Executing operation listarFuncionesEspectador");
        System.out.println(arg0);
        try {
            publicadores.DtFuncionArray _return = new publicadores.DtFuncionArray();
            java.util.List<publicadores.DtFuncion> _returnItem = new java.util.ArrayList<publicadores.DtFuncion>();
            publicadores.DtFuncion _returnItemVal1 = new publicadores.DtFuncion();
            java.util.List<java.lang.String> _returnItemVal1ArtistasInvitados = new java.util.ArrayList<java.lang.String>();
            _returnItemVal1.getArtistasInvitados().addAll(_returnItemVal1ArtistasInvitados);
            _returnItemVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:10:41.916-03:00"));
            _returnItemVal1.setFechaReg(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:10:41.916-03:00"));
            _returnItemVal1.setFechaRegString("FechaRegString746959503");
            _returnItemVal1.setFechaString("FechaString-1894554888");
            _returnItemVal1.setHoraIni(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:10:41.917-03:00"));
            _returnItemVal1.setHoraIniString("HoraIniString-707656482");
            _returnItemVal1.setNombre("Nombre-343653780");
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#altaFuncion()*
     */
    public void altaFuncion() {
        LOG.info("Executing operation altaFuncion");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#listarEspectaculos(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarEspectaculos(java.lang.String arg0) throws PlataformaNoExisteException_Exception   {
        LOG.info("Executing operation listarEspectaculos");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-2066955939";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PlataformaNoExisteException_Exception("PlataformaNoExisteException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#seleccionarEspectaculo(java.lang.String arg0)*
     */
    public void seleccionarEspectaculo(java.lang.String arg0) throws EspectaculoNoValidoException_Exception   {
        LOG.info("Executing operation seleccionarEspectaculo");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EspectaculoNoValidoException_Exception("EspectaculoNoValidoException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#listarEspectaculosPorArtista(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarEspectaculosPorArtista(java.lang.String arg0) throws Exception_Exception   {
        LOG.info("Executing operation listarEspectaculosPorArtista");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal2106461837";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#altaRegistro(net.java.dev.jaxb.array.IntArray arg0)*
     */
    public void altaRegistro(net.java.dev.jaxb.array.IntArray arg0) throws Exception_Exception   {
        LOG.info("Executing operation altaRegistro");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#listarFunciones()*
     */
    public net.java.dev.jaxb.array.StringArray listarFunciones() {
        LOG.info("Executing operation listarFunciones");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal53222263";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#listarEspectadores()*
     */
    public net.java.dev.jaxb.array.StringArray listarEspectadores() {
        LOG.info("Executing operation listarEspectadores");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1245427052";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#listarPaquetes(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarPaquetes(java.lang.String arg0) {
        LOG.info("Executing operation listarPaquetes");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-664314876";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#ingresarFuncion(publicadores.DtFuncion arg0, byte[] arg1)*
     */
    public void ingresarFuncion(DtFuncion arg0, byte[] arg1) throws FuncionNoValidaException_Exception   {
        LOG.info("Executing operation ingresarFuncion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FuncionNoValidaException_Exception("FuncionNoValidaException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#ingresarArtista(java.lang.String arg0)*
     */
    public void ingresarArtista(java.lang.String arg0) throws Exception_Exception,  UsuarioNoExisteException_Exception   {
        LOG.info("Executing operation ingresarArtista");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
        //throw new UsuarioNoExisteException_Exception("UsuarioNoExisteException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorFuncionPublish#listarFuncionesVigentes()*
     */
    public net.java.dev.jaxb.array.StringArray listarFuncionesVigentes() {
        LOG.info("Executing operation listarFuncionesVigentes");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal371236754";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
