
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package publicadores;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:10.888-03:00
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
                      serviceName = "ControladorPlataformaPublishService",
                      portName = "ControladorPlataformaPublishPort",
                      targetNamespace = "http://publicadores/",
                      wsdlLocation = "http://localhost:3030/controladorPlat?wsdl",
                      endpointInterface = "publicadores.ControladorPlataformaPublish")

public class ControladorPlataformaPublishPortImpl implements ControladorPlataformaPublish {

    private static final Logger LOG = Logger.getLogger(ControladorPlataformaPublishPortImpl.class.getName());

    /* (non-Javadoc)
     * @see publicadores.ControladorPlataformaPublish#altaPlataforma()*
     */
    public void altaPlataforma() throws PlataformaNoValidaException_Exception   {
        LOG.info("Executing operation altaPlataforma");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PlataformaNoValidaException_Exception("PlataformaNoValidaException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPlataformaPublish#listaPlataformas()*
     */
    public net.java.dev.jaxb.array.StringArray listaPlataformas() {
        LOG.info("Executing operation listaPlataformas");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1055183185";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPlataformaPublish#chequearDisponibilidadPlataforma(java.lang.String arg0)*
     */
    public boolean chequearDisponibilidadPlataforma(java.lang.String arg0) throws PlataformaNoValidaException_Exception   {
        LOG.info("Executing operation chequearDisponibilidadPlataforma");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PlataformaNoValidaException_Exception("PlataformaNoValidaException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorPlataformaPublish#ingresarDatosPlataforma(publicadores.DtPlataforma arg0)*
     */
    public void ingresarDatosPlataforma(DtPlataforma arg0) throws PlataformaNoValidaException_Exception   {
        LOG.info("Executing operation ingresarDatosPlataforma");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PlataformaNoValidaException_Exception("PlataformaNoValidaException...");
    }

}
