package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:11:11.841-03:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://publicadores/", name = "ControladorUsuarioPublish")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ControladorUsuarioPublish {

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/seleccionarUsuarioRequest", output = "http://publicadores/ControladorUsuarioPublish/seleccionarUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtUsuario seleccionarUsuario(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/seguirUsuarioRequest", output = "http://publicadores/ControladorUsuarioPublish/seguirUsuarioResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorUsuarioPublish/seguirUsuario/Fault/Exception")})
    public void seguirUsuario(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/mostrarRegistrosEspectadorsRequest", output = "http://publicadores/ControladorUsuarioPublish/mostrarRegistrosEspectadorsResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtRegistroArray mostrarRegistrosEspectadors(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/listarSeguidosRequest", output = "http://publicadores/ControladorUsuarioPublish/listarSeguidosResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarSeguidos(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/listarSeguidoresRequest", output = "http://publicadores/ControladorUsuarioPublish/listarSeguidoresResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarSeguidores(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/listarArtistaRequest", output = "http://publicadores/ControladorUsuarioPublish/listarArtistaResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarArtista()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/getImagenUsuarioRequest", output = "http://publicadores/ControladorUsuarioPublish/getImagenUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public java.lang.String getImagenUsuario(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/whoamiRequest", output = "http://publicadores/ControladorUsuarioPublish/whoamiResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtUsuario whoami()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/cerrarSesionRequest", output = "http://publicadores/ControladorUsuarioPublish/cerrarSesionResponse")
    public void cerrarSesion()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/ingresarDatosArtistaRequest", output = "http://publicadores/ControladorUsuarioPublish/ingresarDatosArtistaResponse")
    public void ingresarDatosArtista(

        @WebParam(partName = "arg0", name = "arg0")
        DtArtista arg0,
        @WebParam(partName = "arg1", name = "arg1")
        byte[] arg1
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/chequearDisponibilidadCorreoRequest", output = "http://publicadores/ControladorUsuarioPublish/chequearDisponibilidadCorreoResponse", fault = {@FaultAction(className = CorreoExisteException_Exception.class, value = "http://publicadores/ControladorUsuarioPublish/chequearDisponibilidadCorreo/Fault/CorreoExisteException")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public boolean chequearDisponibilidadCorreo(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws CorreoExisteException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/mostrarEspectaculosOrganizadosRequest", output = "http://publicadores/ControladorUsuarioPublish/mostrarEspectaculosOrganizadosResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray mostrarEspectaculosOrganizados(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/iniciarSesionRequest", output = "http://publicadores/ControladorUsuarioPublish/iniciarSesionResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorUsuarioPublish/iniciarSesion/Fault/Exception")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public java.lang.String iniciarSesion(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/listarUsuariosRequest", output = "http://publicadores/ControladorUsuarioPublish/listarUsuariosResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarUsuarios()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/listarPaquetesRequest", output = "http://publicadores/ControladorUsuarioPublish/listarPaquetesResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarPaquetes(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/modificarUsuarioRequest", output = "http://publicadores/ControladorUsuarioPublish/modificarUsuarioResponse")
    public void modificarUsuario(

        @WebParam(partName = "arg0", name = "arg0")
        DtUsuario arg0,
        @WebParam(partName = "arg1", name = "arg1")
        byte[] arg1
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/chequearDisponibilidadNicknameRequest", output = "http://publicadores/ControladorUsuarioPublish/chequearDisponibilidadNicknameResponse", fault = {@FaultAction(className = UsuarioExisteException_Exception.class, value = "http://publicadores/ControladorUsuarioPublish/chequearDisponibilidadNickname/Fault/UsuarioExisteException")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public boolean chequearDisponibilidadNickname(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws UsuarioExisteException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/ingresarDatosEspectadorRequest", output = "http://publicadores/ControladorUsuarioPublish/ingresarDatosEspectadorResponse")
    public void ingresarDatosEspectador(

        @WebParam(partName = "arg0", name = "arg0")
        DtEspectador arg0,
        @WebParam(partName = "arg1", name = "arg1")
        byte[] arg1
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/altaUsuarioRequest", output = "http://publicadores/ControladorUsuarioPublish/altaUsuarioResponse")
    public void altaUsuario()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/dejarSeguirUsuarioRequest", output = "http://publicadores/ControladorUsuarioPublish/dejarSeguirUsuarioResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorUsuarioPublish/dejarSeguirUsuario/Fault/Exception")})
    public void dejarSeguirUsuario(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorUsuarioPublish/altaUsuarioWSRequest", output = "http://publicadores/ControladorUsuarioPublish/altaUsuarioWSResponse")
    public void altaUsuarioWS(

        @WebParam(partName = "arg0", name = "arg0")
        DtUsuario arg0,
        @WebParam(partName = "arg1", name = "arg1")
        byte[] arg1
    );
}
