
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package publicadores;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:11:11.810-03:00
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
                      serviceName = "ControladorUsuarioPublishService",
                      portName = "ControladorUsuarioPublishPort",
                      targetNamespace = "http://publicadores/",
                      wsdlLocation = "http://localhost:3030/controladorUsuario?wsdl",
                      endpointInterface = "publicadores.ControladorUsuarioPublish")

public class ControladorUsuarioPublishPortImpl implements ControladorUsuarioPublish {

    private static final Logger LOG = Logger.getLogger(ControladorUsuarioPublishPortImpl.class.getName());

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#seleccionarUsuario(java.lang.String arg0)*
     */
    public publicadores.DtUsuario seleccionarUsuario(java.lang.String arg0) {
        LOG.info("Executing operation seleccionarUsuario");
        System.out.println(arg0);
        try {
            publicadores.DtUsuario _return = new publicadores.DtUsuario();
            _return.setApellido("Apellido367623152");
            _return.setFnac(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:11:11.824-03:00"));
            _return.setMail("Mail-1373987964");
            _return.setNickName("NickName451083536");
            _return.setNombre("Nombre356190452");
            _return.setPasswd("Passwd-745055179");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#seguirUsuario(java.lang.String arg0)*
     */
    public void seguirUsuario(java.lang.String arg0) throws Exception_Exception   {
        LOG.info("Executing operation seguirUsuario");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#mostrarRegistrosEspectadors(java.lang.String arg0)*
     */
    public publicadores.DtRegistroArray mostrarRegistrosEspectadors(java.lang.String arg0) {
        LOG.info("Executing operation mostrarRegistrosEspectadors");
        System.out.println(arg0);
        try {
            publicadores.DtRegistroArray _return = new publicadores.DtRegistroArray();
            java.util.List<publicadores.DtRegistro> _returnItem = new java.util.ArrayList<publicadores.DtRegistro>();
            publicadores.DtRegistro _returnItemVal1 = new publicadores.DtRegistro();
            _returnItemVal1.setCosto(0.9543954f);
            _returnItemVal1.setFechaReg(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:11:11.827-03:00"));
            _returnItemVal1.setNombreFuncion("NombreFuncion842079776");
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#listarSeguidos(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarSeguidos(java.lang.String arg0) {
        LOG.info("Executing operation listarSeguidos");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-707219526";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#listarSeguidores(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarSeguidores(java.lang.String arg0) {
        LOG.info("Executing operation listarSeguidores");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-531294209";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#listarArtista()*
     */
    public net.java.dev.jaxb.array.StringArray listarArtista() {
        LOG.info("Executing operation listarArtista");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1958257951";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#getImagenUsuario(java.lang.String arg0)*
     */
    public java.lang.String getImagenUsuario(java.lang.String arg0) {
        LOG.info("Executing operation getImagenUsuario");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return190385338";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#whoami()*
     */
    public publicadores.DtUsuario whoami() {
        LOG.info("Executing operation whoami");
        try {
            publicadores.DtUsuario _return = new publicadores.DtUsuario();
            _return.setApellido("Apellido1037396097");
            _return.setFnac(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:11:11.832-03:00"));
            _return.setMail("Mail929752767");
            _return.setNickName("NickName249885117");
            _return.setNombre("Nombre1491435520");
            _return.setPasswd("Passwd1470184530");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#cerrarSesion()*
     */
    public void cerrarSesion() {
        LOG.info("Executing operation cerrarSesion");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#ingresarDatosArtista(publicadores.DtArtista arg0, byte[] arg1)*
     */
    public void ingresarDatosArtista(DtArtista arg0, byte[] arg1) {
        LOG.info("Executing operation ingresarDatosArtista");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#chequearDisponibilidadCorreo(java.lang.String arg0)*
     */
    public boolean chequearDisponibilidadCorreo(java.lang.String arg0) throws CorreoExisteException_Exception   {
        LOG.info("Executing operation chequearDisponibilidadCorreo");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CorreoExisteException_Exception("CorreoExisteException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#mostrarEspectaculosOrganizados(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray mostrarEspectaculosOrganizados(java.lang.String arg0) {
        LOG.info("Executing operation mostrarEspectaculosOrganizados");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1962255777";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#iniciarSesion(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String iniciarSesion(java.lang.String arg0, java.lang.String arg1) throws Exception_Exception   {
        LOG.info("Executing operation iniciarSesion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-431767953";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#listarUsuarios()*
     */
    public net.java.dev.jaxb.array.StringArray listarUsuarios() {
        LOG.info("Executing operation listarUsuarios");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal2035608788";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#listarPaquetes(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarPaquetes(java.lang.String arg0) {
        LOG.info("Executing operation listarPaquetes");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1994084440";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#modificarUsuario(publicadores.DtUsuario arg0, byte[] arg1)*
     */
    public void modificarUsuario(DtUsuario arg0, byte[] arg1) {
        LOG.info("Executing operation modificarUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#chequearDisponibilidadNickname(java.lang.String arg0)*
     */
    public boolean chequearDisponibilidadNickname(java.lang.String arg0) throws UsuarioExisteException_Exception   {
        LOG.info("Executing operation chequearDisponibilidadNickname");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UsuarioExisteException_Exception("UsuarioExisteException...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#ingresarDatosEspectador(publicadores.DtEspectador arg0, byte[] arg1)*
     */
    public void ingresarDatosEspectador(DtEspectador arg0, byte[] arg1) {
        LOG.info("Executing operation ingresarDatosEspectador");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#altaUsuario()*
     */
    public void altaUsuario() {
        LOG.info("Executing operation altaUsuario");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#dejarSeguirUsuario(java.lang.String arg0)*
     */
    public void dejarSeguirUsuario(java.lang.String arg0) throws Exception_Exception   {
        LOG.info("Executing operation dejarSeguirUsuario");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see publicadores.ControladorUsuarioPublish#altaUsuarioWS(publicadores.DtUsuario arg0, byte[] arg1)*
     */
    public void altaUsuarioWS(DtUsuario arg0, byte[] arg1) {
        LOG.info("Executing operation altaUsuarioWS");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
