
package publicadores;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:11:11.710-03:00
 * Generated source version: 3.4.4
 *
 */
public final class ControladorUsuarioPublish_ControladorUsuarioPublishPort_Client {

    private static final QName SERVICE_NAME = new QName("http://publicadores/", "ControladorUsuarioPublishService");

    private ControladorUsuarioPublish_ControladorUsuarioPublishPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ControladorUsuarioPublishService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ControladorUsuarioPublishService ss = new ControladorUsuarioPublishService(wsdlURL, SERVICE_NAME);
        ControladorUsuarioPublish port = ss.getControladorUsuarioPublishPort();

        {
        System.out.println("Invoking seleccionarUsuario...");
        java.lang.String _seleccionarUsuario_arg0 = "_seleccionarUsuario_arg01595071414";
        publicadores.DtUsuario _seleccionarUsuario__return = port.seleccionarUsuario(_seleccionarUsuario_arg0);
        System.out.println("seleccionarUsuario.result=" + _seleccionarUsuario__return);


        }
        {
        System.out.println("Invoking seguirUsuario...");
        java.lang.String _seguirUsuario_arg0 = "_seguirUsuario_arg0-1260642631";
        try {
            port.seguirUsuario(_seguirUsuario_arg0);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking mostrarRegistrosEspectadors...");
        java.lang.String _mostrarRegistrosEspectadors_arg0 = "_mostrarRegistrosEspectadors_arg0-1913178186";
        publicadores.DtRegistroArray _mostrarRegistrosEspectadors__return = port.mostrarRegistrosEspectadors(_mostrarRegistrosEspectadors_arg0);
        System.out.println("mostrarRegistrosEspectadors.result=" + _mostrarRegistrosEspectadors__return);


        }
        {
        System.out.println("Invoking listarSeguidos...");
        java.lang.String _listarSeguidos_arg0 = "_listarSeguidos_arg0-9973687";
        net.java.dev.jaxb.array.StringArray _listarSeguidos__return = port.listarSeguidos(_listarSeguidos_arg0);
        System.out.println("listarSeguidos.result=" + _listarSeguidos__return);


        }
        {
        System.out.println("Invoking listarSeguidores...");
        java.lang.String _listarSeguidores_arg0 = "_listarSeguidores_arg0555542035";
        net.java.dev.jaxb.array.StringArray _listarSeguidores__return = port.listarSeguidores(_listarSeguidores_arg0);
        System.out.println("listarSeguidores.result=" + _listarSeguidores__return);


        }
        {
        System.out.println("Invoking listarArtista...");
        net.java.dev.jaxb.array.StringArray _listarArtista__return = port.listarArtista();
        System.out.println("listarArtista.result=" + _listarArtista__return);


        }
        {
        System.out.println("Invoking getImagenUsuario...");
        java.lang.String _getImagenUsuario_arg0 = "_getImagenUsuario_arg0535015655";
        java.lang.String _getImagenUsuario__return = port.getImagenUsuario(_getImagenUsuario_arg0);
        System.out.println("getImagenUsuario.result=" + _getImagenUsuario__return);


        }
        {
        System.out.println("Invoking whoami...");
        publicadores.DtUsuario _whoami__return = port.whoami();
        System.out.println("whoami.result=" + _whoami__return);


        }
        {
        System.out.println("Invoking cerrarSesion...");
        port.cerrarSesion();


        }
        {
        System.out.println("Invoking ingresarDatosArtista...");
        publicadores.DtArtista _ingresarDatosArtista_arg0 = new publicadores.DtArtista();
        _ingresarDatosArtista_arg0.setApellido("Apellido-1001343449");
        _ingresarDatosArtista_arg0.setFnac(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:11:11.780-03:00"));
        _ingresarDatosArtista_arg0.setMail("Mail1211756680");
        _ingresarDatosArtista_arg0.setNickName("NickName1217077369");
        _ingresarDatosArtista_arg0.setNombre("Nombre7794520");
        _ingresarDatosArtista_arg0.setPasswd("Passwd-1613604194");
        _ingresarDatosArtista_arg0.setDescripcion("Descripcion1729790972");
        _ingresarDatosArtista_arg0.setUrl("Url-526970743");
        _ingresarDatosArtista_arg0.setBiografia("Biografia1255697503");
        byte[] _ingresarDatosArtista_arg1 = new byte[] {};
        port.ingresarDatosArtista(_ingresarDatosArtista_arg0, _ingresarDatosArtista_arg1);


        }
        {
        System.out.println("Invoking chequearDisponibilidadCorreo...");
        java.lang.String _chequearDisponibilidadCorreo_arg0 = "_chequearDisponibilidadCorreo_arg01177925249";
        try {
            boolean _chequearDisponibilidadCorreo__return = port.chequearDisponibilidadCorreo(_chequearDisponibilidadCorreo_arg0);
            System.out.println("chequearDisponibilidadCorreo.result=" + _chequearDisponibilidadCorreo__return);

        } catch (CorreoExisteException_Exception e) {
            System.out.println("Expected exception: CorreoExisteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking mostrarEspectaculosOrganizados...");
        java.lang.String _mostrarEspectaculosOrganizados_arg0 = "_mostrarEspectaculosOrganizados_arg01081762051";
        net.java.dev.jaxb.array.StringArray _mostrarEspectaculosOrganizados__return = port.mostrarEspectaculosOrganizados(_mostrarEspectaculosOrganizados_arg0);
        System.out.println("mostrarEspectaculosOrganizados.result=" + _mostrarEspectaculosOrganizados__return);


        }
        {
        System.out.println("Invoking iniciarSesion...");
        java.lang.String _iniciarSesion_arg0 = "_iniciarSesion_arg0-472858846";
        java.lang.String _iniciarSesion_arg1 = "_iniciarSesion_arg1-1949870547";
        try {
            java.lang.String _iniciarSesion__return = port.iniciarSesion(_iniciarSesion_arg0, _iniciarSesion_arg1);
            System.out.println("iniciarSesion.result=" + _iniciarSesion__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking listarUsuarios...");
        net.java.dev.jaxb.array.StringArray _listarUsuarios__return = port.listarUsuarios();
        System.out.println("listarUsuarios.result=" + _listarUsuarios__return);


        }
        {
        System.out.println("Invoking listarPaquetes...");
        java.lang.String _listarPaquetes_arg0 = "_listarPaquetes_arg0-840387828";
        net.java.dev.jaxb.array.StringArray _listarPaquetes__return = port.listarPaquetes(_listarPaquetes_arg0);
        System.out.println("listarPaquetes.result=" + _listarPaquetes__return);


        }
        {
        System.out.println("Invoking modificarUsuario...");
        publicadores.DtUsuario _modificarUsuario_arg0 = new publicadores.DtUsuario();
        _modificarUsuario_arg0.setApellido("Apellido-1120609428");
        _modificarUsuario_arg0.setFnac(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:11:11.785-03:00"));
        _modificarUsuario_arg0.setMail("Mail2030486570");
        _modificarUsuario_arg0.setNickName("NickName579768643");
        _modificarUsuario_arg0.setNombre("Nombre-2094003011");
        _modificarUsuario_arg0.setPasswd("Passwd-1387649532");
        byte[] _modificarUsuario_arg1 = new byte[] {};
        port.modificarUsuario(_modificarUsuario_arg0, _modificarUsuario_arg1);


        }
        {
        System.out.println("Invoking chequearDisponibilidadNickname...");
        java.lang.String _chequearDisponibilidadNickname_arg0 = "_chequearDisponibilidadNickname_arg01019005582";
        try {
            boolean _chequearDisponibilidadNickname__return = port.chequearDisponibilidadNickname(_chequearDisponibilidadNickname_arg0);
            System.out.println("chequearDisponibilidadNickname.result=" + _chequearDisponibilidadNickname__return);

        } catch (UsuarioExisteException_Exception e) {
            System.out.println("Expected exception: UsuarioExisteException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking ingresarDatosEspectador...");
        publicadores.DtEspectador _ingresarDatosEspectador_arg0 = new publicadores.DtEspectador();
        _ingresarDatosEspectador_arg0.setApellido("Apellido784762401");
        _ingresarDatosEspectador_arg0.setFnac(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:11:11.787-03:00"));
        _ingresarDatosEspectador_arg0.setMail("Mail-60055310");
        _ingresarDatosEspectador_arg0.setNickName("NickName-1847215759");
        _ingresarDatosEspectador_arg0.setNombre("Nombre-1447571322");
        _ingresarDatosEspectador_arg0.setPasswd("Passwd1283036739");
        byte[] _ingresarDatosEspectador_arg1 = new byte[] {};
        port.ingresarDatosEspectador(_ingresarDatosEspectador_arg0, _ingresarDatosEspectador_arg1);


        }
        {
        System.out.println("Invoking altaUsuario...");
        port.altaUsuario();


        }
        {
        System.out.println("Invoking dejarSeguirUsuario...");
        java.lang.String _dejarSeguirUsuario_arg0 = "_dejarSeguirUsuario_arg01604284879";
        try {
            port.dejarSeguirUsuario(_dejarSeguirUsuario_arg0);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking altaUsuarioWS...");
        publicadores.DtUsuario _altaUsuarioWS_arg0 = new publicadores.DtUsuario();
        _altaUsuarioWS_arg0.setApellido("Apellido-1604070339");
        _altaUsuarioWS_arg0.setFnac(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2021-11-02T02:11:11.788-03:00"));
        _altaUsuarioWS_arg0.setMail("Mail-1109940195");
        _altaUsuarioWS_arg0.setNickName("NickName535194701");
        _altaUsuarioWS_arg0.setNombre("Nombre-2144435099");
        _altaUsuarioWS_arg0.setPasswd("Passwd1336305717");
        byte[] _altaUsuarioWS_arg1 = new byte[] {};
        port.altaUsuarioWS(_altaUsuarioWS_arg0, _altaUsuarioWS_arg1);


        }

        System.exit(0);
    }

}
