package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:09:52.715-03:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://publicadores/", name = "ControladorPaquetePublish")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ControladorPaquetePublish {

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/chequearDisponibilidadPaqueteRequest", output = "http://publicadores/ControladorPaquetePublish/chequearDisponibilidadPaqueteResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public boolean chequearDisponibilidadPaquete(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/agregarEspectaculoAPaqueteRequest", output = "http://publicadores/ControladorPaquetePublish/agregarEspectaculoAPaqueteResponse")
    public void agregarEspectaculoAPaquete(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/listarPaquetesVigentesRequest", output = "http://publicadores/ControladorPaquetePublish/listarPaquetesVigentesResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarPaquetesVigentes()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/getImagenPaqueteRequest", output = "http://publicadores/ControladorPaquetePublish/getImagenPaqueteResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorPaquetePublish/getImagenPaquete/Fault/Exception")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public java.lang.String getImagenPaquete(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/seleccionarEspectaculoRequest", output = "http://publicadores/ControladorPaquetePublish/seleccionarEspectaculoResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorPaquetePublish/seleccionarEspectaculo/Fault/Exception")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtEspectaculoCompleto seleccionarEspectaculo(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/seleccionarPlataformaRequest", output = "http://publicadores/ControladorPaquetePublish/seleccionarPlataformaResponse", fault = {@FaultAction(className = PlataformaNoValidaException_Exception.class, value = "http://publicadores/ControladorPaquetePublish/seleccionarPlataforma/Fault/PlataformaNoValidaException")})
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray seleccionarPlataforma(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    ) throws PlataformaNoValidaException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/seleccionarPaqueteRequest", output = "http://publicadores/ControladorPaquetePublish/seleccionarPaqueteResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public DtPaquete seleccionarPaquete(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/comprarPaqueteRequest", output = "http://publicadores/ControladorPaquetePublish/comprarPaqueteResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorPaquetePublish/comprarPaquete/Fault/Exception")})
    public void comprarPaquete(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/listarPaquetesRequest", output = "http://publicadores/ControladorPaquetePublish/listarPaquetesResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarPaquetes()
;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/espectaculosDelPaqueteRequest", output = "http://publicadores/ControladorPaquetePublish/espectaculosDelPaqueteResponse")
    @WebResult(name = "return", targetNamespace = "http://publicadores/", partName = "return")
    public net.java.dev.jaxb.array.StringArray espectaculosDelPaquete(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/altaPaqueteRequest", output = "http://publicadores/ControladorPaquetePublish/altaPaqueteResponse", fault = {@FaultAction(className = PaqueteNoValidoException_Exception.class, value = "http://publicadores/ControladorPaquetePublish/altaPaquete/Fault/PaqueteNoValidoException")})
    public void altaPaquete()
 throws PaqueteNoValidoException_Exception;

    @WebMethod
    @Action(input = "http://publicadores/ControladorPaquetePublish/ingresarDatosPaqueteRequest", output = "http://publicadores/ControladorPaquetePublish/ingresarDatosPaqueteResponse", fault = {@FaultAction(className = PaqueteNoValidoException_Exception.class, value = "http://publicadores/ControladorPaquetePublish/ingresarDatosPaquete/Fault/PaqueteNoValidoException")})
    public void ingresarDatosPaquete(

        @WebParam(partName = "arg0", name = "arg0")
        DtPaquete arg0,
        @WebParam(partName = "arg1", name = "arg1")
        byte[] arg1
    ) throws PaqueteNoValidoException_Exception;
}
