package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:09:52.724-03:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ControladorPaquetePublishService",
                  wsdlLocation = "http://localhost:3030/controladorPaq?wsdl",
                  targetNamespace = "http://publicadores/")
public class ControladorPaquetePublishService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://publicadores/", "ControladorPaquetePublishService");
    public final static QName ControladorPaquetePublishPort = new QName("http://publicadores/", "ControladorPaquetePublishPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:3030/controladorPaq?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControladorPaquetePublishService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:3030/controladorPaq?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControladorPaquetePublishService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControladorPaquetePublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorPaquetePublishService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ControladorPaquetePublishService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ControladorPaquetePublishService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ControladorPaquetePublishService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ControladorPaquetePublish
     */
    @WebEndpoint(name = "ControladorPaquetePublishPort")
    public ControladorPaquetePublish getControladorPaquetePublishPort() {
        return super.getPort(ControladorPaquetePublishPort, ControladorPaquetePublish.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorPaquetePublish
     */
    @WebEndpoint(name = "ControladorPaquetePublishPort")
    public ControladorPaquetePublish getControladorPaquetePublishPort(WebServiceFeature... features) {
        return super.getPort(ControladorPaquetePublishPort, ControladorPaquetePublish.class, features);
    }

}
