
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:11:11.797-03:00
 * Generated source version: 3.4.4
 */

@WebFault(name = "CorreoExisteException", targetNamespace = "http://publicadores/")
public class CorreoExisteException_Exception extends java.lang.Exception {

    private publicadores.CorreoExisteException faultInfo;

    public CorreoExisteException_Exception() {
        super();
    }

    public CorreoExisteException_Exception(String message) {
        super(message);
    }

    public CorreoExisteException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CorreoExisteException_Exception(String message, publicadores.CorreoExisteException correoExisteException) {
        super(message);
        this.faultInfo = correoExisteException;
    }

    public CorreoExisteException_Exception(String message, publicadores.CorreoExisteException correoExisteException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = correoExisteException;
    }

    public publicadores.CorreoExisteException getFaultInfo() {
        return this.faultInfo;
    }
}
