
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:41.881-03:00
 * Generated source version: 3.4.4
 */

@WebFault(name = "EspectaculoNoValidoException", targetNamespace = "http://publicadores/")
public class EspectaculoNoValidoException_Exception extends java.lang.Exception {

    private publicadores.EspectaculoNoValidoException faultInfo;

    public EspectaculoNoValidoException_Exception() {
        super();
    }

    public EspectaculoNoValidoException_Exception(String message) {
        super(message);
    }

    public EspectaculoNoValidoException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EspectaculoNoValidoException_Exception(String message, publicadores.EspectaculoNoValidoException espectaculoNoValidoException) {
        super(message);
        this.faultInfo = espectaculoNoValidoException;
    }

    public EspectaculoNoValidoException_Exception(String message, publicadores.EspectaculoNoValidoException espectaculoNoValidoException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = espectaculoNoValidoException;
    }

    public publicadores.EspectaculoNoValidoException getFaultInfo() {
        return this.faultInfo;
    }
}
