
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:27.043-03:00
 * Generated source version: 3.4.4
 */

@WebFault(name = "PaqueteNoValidoException", targetNamespace = "http://publicadores/")
public class PaqueteNoValidoException_Exception extends java.lang.Exception {

    private publicadores.PaqueteNoValidoException faultInfo;

    public PaqueteNoValidoException_Exception() {
        super();
    }

    public PaqueteNoValidoException_Exception(String message) {
        super(message);
    }

    public PaqueteNoValidoException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PaqueteNoValidoException_Exception(String message, publicadores.PaqueteNoValidoException paqueteNoValidoException) {
        super(message);
        this.faultInfo = paqueteNoValidoException;
    }

    public PaqueteNoValidoException_Exception(String message, publicadores.PaqueteNoValidoException paqueteNoValidoException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = paqueteNoValidoException;
    }

    public publicadores.PaqueteNoValidoException getFaultInfo() {
        return this.faultInfo;
    }
}
