
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:41.874-03:00
 * Generated source version: 3.4.4
 */

@WebFault(name = "PlataformaNoExisteException", targetNamespace = "http://publicadores/")
public class PlataformaNoExisteException_Exception extends java.lang.Exception {

    private publicadores.PlataformaNoExisteException faultInfo;

    public PlataformaNoExisteException_Exception() {
        super();
    }

    public PlataformaNoExisteException_Exception(String message) {
        super(message);
    }

    public PlataformaNoExisteException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PlataformaNoExisteException_Exception(String message, publicadores.PlataformaNoExisteException plataformaNoExisteException) {
        super(message);
        this.faultInfo = plataformaNoExisteException;
    }

    public PlataformaNoExisteException_Exception(String message, publicadores.PlataformaNoExisteException plataformaNoExisteException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = plataformaNoExisteException;
    }

    public publicadores.PlataformaNoExisteException getFaultInfo() {
        return this.faultInfo;
    }
}
