
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-11-02T02:10:41.888-03:00
 * Generated source version: 3.4.4
 */

@WebFault(name = "UsuarioNoExisteException", targetNamespace = "http://publicadores/")
public class UsuarioNoExisteException_Exception extends java.lang.Exception {

    private publicadores.UsuarioNoExisteException faultInfo;

    public UsuarioNoExisteException_Exception() {
        super();
    }

    public UsuarioNoExisteException_Exception(String message) {
        super(message);
    }

    public UsuarioNoExisteException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UsuarioNoExisteException_Exception(String message, publicadores.UsuarioNoExisteException usuarioNoExisteException) {
        super(message);
        this.faultInfo = usuarioNoExisteException;
    }

    public UsuarioNoExisteException_Exception(String message, publicadores.UsuarioNoExisteException usuarioNoExisteException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = usuarioNoExisteException;
    }

    public publicadores.UsuarioNoExisteException getFaultInfo() {
        return this.faultInfo;
    }
}
